<script setup lang="ts">
import { usePublicContentService } from '~/services/public-content'
const route = useRoute(); const id = Number(route.params.id)
if (!Number.isSafeInteger(id) || id < 1) throw createError({ statusCode: 404, statusMessage: 'Noticia no encontrada' })
const service = usePublicContentService()
const { data: news, status, error, refresh } = await useAsyncData(`public-news-${id}`, () => service.newsById(id), { default: () => null })
useSeoMeta({ title: () => news.value?.title || 'Noticia', description: () => news.value?.summary || 'Consulta una publicación de AsoQuímica UVG.' })
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('es-GT', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(value)) : 'Fecha por confirmar'
</script>
<template><div><PageHero eyebrow="Noticias y anuncios" title="Publicación" description="Información publicada por AsoQuímica UVG." /><AppSection title="Detalle de la publicación"><StatePanel v-if="status === 'pending'" title="Cargando publicación" message="Consultando la información publicada." /><StatePanel v-else-if="error" role="alert" title="No encontramos esta publicación" message="Es posible que no exista, haya sido archivada o ya no esté disponible."><AppButton to="/noticias" variant="secondary">Volver a noticias</AppButton><button @click="() => refresh()">Reintentar</button></StatePanel><article v-else-if="news" class="news-detail"><div class="news-detail__meta"><EyebrowBadge :text="news.category.name" /><time :datetime="news.publishedAt || news.createdAt">Publicado el {{ formatDate(news.publishedAt) }}</time></div><h1>{{ news.title }}</h1><p class="news-detail__summary">{{ news.summary }}</p><div class="news-detail__content">{{ news.content }}</div><footer>Publicado por {{ news.createdBy.name }}</footer><AppButton to="/noticias" variant="secondary">← Ver todas las noticias</AppButton></article></AppSection></div></template>
<style scoped>.news-detail { display: grid; gap: 1.4rem; max-width: 52rem; margin-inline: auto; padding: clamp(1.25rem, 4vw, 2.5rem); background: white; border: 1px solid var(--color-border); border-radius: var(--radius-lg); box-shadow: var(--shadow); }.news-detail__meta { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: .75rem; color: var(--color-muted); font-size: .92rem; }.news-detail h1 { font-size: clamp(2rem, 6vw, 3.6rem); }.news-detail__summary { color: var(--color-muted); font-size: 1.2rem; }.news-detail__content { white-space: pre-line; font-size: 1.06rem; }.news-detail footer { color: var(--color-muted); font-size: .94rem; } @media (max-width: 620px) { .news-detail { padding: 1.25rem; } }</style>
